CREATE TABLE `student` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) DEFAULT NULL,
  `age` INT(11) DEFAULT '0',
  `own_phone` VARCHAR(11) DEFAULT '0',
  `address` VARCHAR(30) DEFAULT NULL,
  `birthday` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '出生日期',
  PRIMARY KEY (`id`)
)  DEFAULT CHARSET=utf8mb4